import { Skill } from '@/entities/skill';

export const SKILLS_MOCK: Skill[] = [
  {
    id: 'skill-frontend-foundations',
    name: 'Веб-основы (HTML/CSS/JS)',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-architecture',
    name: 'Архитектура приложений',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-state-management',
    name: 'Управление состоянием',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-performance',
    name: 'Оптимизация производительности',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-backend',
    name: 'Бэкенд и API',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-api-design',
    name: 'Проектирование API',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-databases',
    name: 'Базы данных',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-system-design',
    name: 'Системный дизайн',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-devops-basics',
    name: 'DevOps основы',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-architecture',
    name: 'Архитектура мобильных приложений',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-ui',
    name: 'Мобильный UI/UX',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-performance',
    name: 'Оптимизация мобильных приложений',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-release-pipeline',
    name: 'Релизы и публикация',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-automation',
    name: 'Автотесты',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-design',
    name: 'Дизайн тестов',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ci-cd',
    name: 'CI/CD',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-quality-metrics',
    name: 'Метрики качества',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-infra-as-code',
    name: 'Инфраструктура как код',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-observability',
    name: 'Наблюдаемость',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-reliability',
    name: 'Надежность и SLO',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-pipelines',
    name: 'Data pipelines',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-sql',
    name: 'SQL и моделирование',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-warehouse',
    name: 'Хранилища данных',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-stream-processing',
    name: 'Стриминг данных',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-modeling',
    name: 'Модели ML',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-python-data',
    name: 'Python для данных',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-experimentation',
    name: 'Эксперименты и валидация',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mlops',
    name: 'MLOps',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-threat-modeling',
    name: 'Threat Modeling',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-secure-coding',
    name: 'Безопасное кодирование',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-appsec-testing',
    name: 'AppSec тестирование',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-dependency-security',
    name: 'Безопасность зависимостей',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-game-engine',
    name: 'Игровой движок',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-gameplay-programming',
    name: 'Геймплейное программирование',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-graphics',
    name: 'Графика и шейдеры',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-optimization',
    name: 'Оптимизация',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-research',
    name: 'Продуктовое исследование',
    category: 'Продукт',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mentorship',
    name: 'Наставничество',
    category: 'Лидерство',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-communication',
    name: 'Коммуникация',
    category: 'Лидерство',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
];
