import { Skill } from '@/entities/skill';

export const SKILLS_MOCK: Skill[] = [
  {
    id: 'skill-architecture',
    name: 'Фронтенд-архитектура',
    category: 'Инженерия',
    level: 2,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-performance',
    name: 'Оптимизация производительности',
    category: 'Инженерия',
    level: 1,
    maxLevel: 5,
    deps: ['skill-architecture'],
  },
  {
    id: 'skill-backend',
    name: 'Бэкенд и API',
    category: 'Инженерия',
    level: 1,
    maxLevel: 5,
    deps: ['skill-architecture'],
  },
  {
    id: 'skill-system-design',
    name: 'Системное мышление',
    category: 'Инженерия',
    level: 1,
    maxLevel: 5,
    deps: ['skill-architecture'],
  },
  {
    id: 'skill-research',
    name: 'Продуктовое исследование',
    category: 'Продукт',
    level: 3,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mentorship',
    name: 'Наставничество',
    category: 'Лидерство',
    level: 2,
    maxLevel: 5,
    deps: ['skill-research'],
  },
  {
    id: 'skill-communication',
    name: 'Коммуникация',
    category: 'Лидерство',
    level: 1,
    maxLevel: 5,
    deps: [],
  },
];
