import { Skill } from '@/entities/skill';

export const SKILLS_MOCK: Skill[] = [
  {
    id: 'skill-frontend-foundations',
    name: 'Веб-основы (HTML/CSS/JS)',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-architecture',
    name: 'Архитектура приложений',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-state-management',
    name: 'Управление состоянием',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-performance',
    name: 'Оптимизация производительности',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-backend',
    name: 'Бэкенд и API',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-api-design',
    name: 'Проектирование API',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-databases',
    name: 'Базы данных',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-system-design',
    name: 'Системный дизайн',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-devops-basics',
    name: 'DevOps основы',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-architecture',
    name: 'Архитектура мобильных приложений',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-ui',
    name: 'Мобильный UI/UX',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-performance',
    name: 'Оптимизация мобильных приложений',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-release-pipeline',
    name: 'Релизы и публикация',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-automation',
    name: 'Автотесты',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-design',
    name: 'Дизайн тестов',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ci-cd',
    name: 'CI/CD',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-quality-metrics',
    name: 'Метрики качества',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-infra-as-code',
    name: 'Инфраструктура как код',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-observability',
    name: 'Наблюдаемость',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-reliability',
    name: 'Надежность и SLO',
    category: 'Инженерия',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-pipelines',
    name: 'Data pipelines',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-sql',
    name: 'SQL и моделирование',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-warehouse',
    name: 'Хранилища данных',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-stream-processing',
    name: 'Стриминг данных',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-modeling',
    name: 'Модели ML',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-python-data',
    name: 'Python для данных',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-experimentation',
    name: 'Эксперименты и валидация',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mlops',
    name: 'MLOps',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-threat-modeling',
    name: 'Threat Modeling',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-secure-coding',
    name: 'Безопасное кодирование',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-appsec-testing',
    name: 'AppSec тестирование',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-dependency-security',
    name: 'Безопасность зависимостей',
    category: 'Безопасность',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-game-engine',
    name: 'Игровой движок',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-gameplay-programming',
    name: 'Геймплейное программирование',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-graphics',
    name: 'Графика и шейдеры',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-optimization',
    name: 'Оптимизация',
    category: 'Геймдев',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-research',
    name: 'Продуктовое исследование',
    category: 'Продукт',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mentorship',
    name: 'Наставничество',
    category: 'Лидерство',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-communication',
    name: 'Коммуникация',
    category: 'Лидерство',
    level: 0,
    maxLevel: 5,
    deps: [],
  },

  {
    id: 'skill-accessibility',
    name: 'Accessibility',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-advanced-ml',
    name: 'Advanced ML',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ai-gameplay',
    name: 'Ai Gameplay',
    category: '???????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-api-testing',
    name: 'API Testing',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-app-optimization',
    name: 'App Optimization',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-architecture-data',
    name: 'Architecture Data',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-auth-basics',
    name: 'Auth Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-automation',
    name: 'Automation',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-big-data',
    name: 'Big Data',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-bug-reporting',
    name: 'Bug Reporting',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-cache-basics',
    name: 'Cache Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-capacity-planning',
    name: 'Capacity Planning',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-cloud-basics',
    name: 'Cloud Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-code-review-security',
    name: 'Code Review Security',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-component-design',
    name: 'Component Design',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-containerization',
    name: 'Containerization',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-cost-optimization',
    name: 'Cost Optimization',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-cross-platform-architecture',
    name: 'Cross Platform Architecture',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-css-layout',
    name: 'CSS Layout',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-governance',
    name: 'Data Governance',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-modeling',
    name: 'Data Modeling',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-quality',
    name: 'Data Quality',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-data-security',
    name: 'Data Security',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-design-system',
    name: 'Design System',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-disaster-recovery',
    name: 'Disaster Recovery',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-distributed-systems',
    name: 'Distributed Systems',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-engine-optimization',
    name: 'Engine Optimization',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-etl-basics',
    name: 'ETL Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-feature-engineering',
    name: 'Feature Engineering',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-finops',
    name: 'Finops',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-flaky-tests',
    name: 'Flaky Tests',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-frontend-architecture-advanced',
    name: 'Frontend Architecture Advanced',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-frontend-observability',
    name: 'Frontend Observability',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-game-architecture',
    name: 'Game Architecture',
    category: '???????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-game-physics',
    name: 'Game Physics',
    category: '???????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-game-production',
    name: 'Game Production',
    category: '???????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-game-ui',
    name: 'Game UI',
    category: '???????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-git-basics',
    name: 'Git Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-html-semantic',
    name: 'HTML Semantic',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-http-basics',
    name: 'Http Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-iam-basics',
    name: 'IAM Basics',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-incident-response',
    name: 'Incident Response',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-incident-response-security',
    name: 'Incident Response Security',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-kubernetes',
    name: 'Kubernetes',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-lakehouse',
    name: 'Lakehouse',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-level-design',
    name: 'Level Design',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-linux-basics',
    name: 'Linux Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-live-ops',
    name: 'Live Ops',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-messaging',
    name: 'Messaging',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-micro-frontend',
    name: 'Micro Frontend',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-data-pipelines',
    name: 'ML Data Pipelines',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-deployment',
    name: 'ML Deployment',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-governance',
    name: 'ML Governance',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-math',
    name: 'ML Math',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-performance',
    name: 'ML Performance',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-product-strategy',
    name: 'ML Product Strategy',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-reliability',
    name: 'ML Reliability',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ml-systems',
    name: 'ML Systems',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-debugging',
    name: 'Mobile Debugging',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-networking',
    name: 'Mobile Networking',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-observability',
    name: 'Mobile Observability',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-platform-basics',
    name: 'Mobile Platform Basics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-security',
    name: 'Mobile Security',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-storage',
    name: 'Mobile Storage',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-testing',
    name: 'Mobile Testing',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-mobile-ux-research',
    name: 'Mobile UX Research',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-model-evaluation',
    name: 'Model Evaluation',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-model-interpretability',
    name: 'Model Interpretability',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-multiplayer',
    name: 'Multiplayer',
    category: '???????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-observability-qa',
    name: 'Observability QA',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-offline-first',
    name: 'Offline First',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-orchestration',
    name: 'Orchestration',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-owasp',
    name: 'OWASP',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-penetration-testing',
    name: 'Penetration Testing',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-performance-backend',
    name: 'Performance Backend',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-performance-data',
    name: 'Performance Data',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-performance-profiling',
    name: 'Performance Profiling',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-performance-testing',
    name: 'Performance Testing',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-platform-engineering',
    name: 'Platform Engineering',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-quality-leadership',
    name: 'Quality Leadership',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-red-team',
    name: 'Red Team',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-reliability-data',
    name: 'Reliability Data',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-rendering-advanced',
    name: 'Rendering Advanced',
    category: '???????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-risk-management',
    name: 'Risk Management',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-routing',
    name: 'Routing',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-scalability',
    name: 'Scalability',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-scale-mobile-teams',
    name: 'Scale Mobile Teams',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-secure-architecture',
    name: 'Secure Architecture',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-security-automation',
    name: 'Security Automation',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-security-backend',
    name: 'Security Backend',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-security-observability',
    name: 'Security Observability',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-security-program',
    name: 'Security Program',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-security-testing',
    name: 'Security Testing',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-sre-metrics',
    name: 'SRE Metrics',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-architecture',
    name: 'Test Architecture',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-data',
    name: 'Test Data',
    category: 'Data',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-frameworks',
    name: 'Test Frameworks',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-test-strategy',
    name: 'Test Strategy',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-testing-backend',
    name: 'Testing Backend',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-testing-ui',
    name: 'Testing UI',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-tools-pipeline',
    name: 'Tools Pipeline',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-ui-testing',
    name: 'UI Testing',
    category: '?????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-vuln-management',
    name: 'Vuln Management',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
  {
    id: 'skill-web-security',
    name: 'Web Security',
    category: '????????????',
    level: 0,
    maxLevel: 5,
    deps: [],
  },
];
