import type { Badge } from '../model/badge.model';

export const BADGES_CATALOG: Badge[] = [
  {
    id: 'session-scenario-sprint',
    title: 'Разогрев',
    description: 'Сессию открыл и разогнал темп решения сценариев.',
    rarity: 'common',
    tags: ['quest', 'session'],
  },
  {
    id: 'session-scenario-focus',
    title: 'Серийный исполнитель',
    description: 'Последовательно закрывал сценарии в одной сессии.',
    rarity: 'rare',
    tags: ['quest', 'session'],
  },
  {
    id: 'session-exam-pass',
    title: 'Турбо-сессия',
    description: 'Сдал экзамен в рамках сессионного квеста.',
    rarity: 'rare',
    tags: ['quest', 'exam'],
  },
  {
    id: 'session-exam-ready',
    title: 'Готов к экзамену',
    description: 'Подтвердил готовность и успешно прошёл экзамен.',
    rarity: 'common',
    tags: ['quest', 'exam'],
  },
  {
    id: 'session-purchase-upgrade',
    title: 'Апгрейд недели',
    description: 'Сделал покупку для ускорения развития.',
    rarity: 'common',
    tags: ['quest', 'shop'],
  },
  {
    id: 'session-purchase-invest',
    title: 'Инвестиция в инструменты',
    description: 'Инвестировал в полезные предметы в сессии.',
    rarity: 'common',
    tags: ['quest', 'shop'],
  },
  {
    id: 'badge_ending_ipo',
    title: 'IPO',
    description: 'Довёл компанию до выхода на биржу.',
    rarity: 'legendary',
    tags: ['ending', 'company'],
  },
  {
    id: 'badge_ending_acq',
    title: 'Поглощение',
    description: 'Компанию купил крупный игрок рынка.',
    rarity: 'epic',
    tags: ['ending', 'company'],
  },
  {
    id: 'badge_ending_oss',
    title: 'Open Source',
    description: 'Открыл продукт миру и сообществу.',
    rarity: 'epic',
    tags: ['ending', 'community'],
  },
  {
    id: 'badge_ending_scandal',
    title: 'Скандал',
    description: 'Репутация пострадала из-за громкого инцидента.',
    rarity: 'rare',
    tags: ['ending', 'risk'],
  },
  {
    id: 'badge_ending_bankrupt',
    title: 'Банкрот',
    description: 'Компания не выдержала финансовой нагрузки.',
    rarity: 'rare',
    tags: ['ending', 'risk'],
  },
  {
    id: 'badge_streak_3',
    title: '3 дня подряд',
    description: 'Активность три дня подряд.',
    rarity: 'common',
    tags: ['streak'],
  },
  {
    id: 'badge_streak_7',
    title: '7 дней подряд',
    description: 'Неделя стабильной активности без пропусков.',
    rarity: 'rare',
    tags: ['streak'],
  },
  {
    id: 'badge_streak_14',
    title: '14 дней подряд',
    description: 'Две недели уверенной серии активности.',
    rarity: 'epic',
    tags: ['streak'],
  },
  {
    id: 'badge_company_first_hire',
    title: 'Первый сотрудник',
    description: 'Нанял первого сотрудника в компанию.',
    rarity: 'common',
    tags: ['company'],
  },
  {
    id: 'badge_company_team_5',
    title: 'Команда из 5',
    description: 'Сформировал команду из пяти сотрудников.',
    rarity: 'rare',
    tags: ['company'],
  },
  {
    id: 'badge_company_cto',
    title: 'CTO',
    description: 'Достиг уровня CTO в компании.',
    rarity: 'legendary',
    tags: ['company'],
  },
  {
    id: 'badge_contract_first',
    title: 'Первый контракт',
    description: 'Выполнил первый контракт компании.',
    rarity: 'common',
    tags: ['contracts'],
  },
  {
    id: 'badge_contract_10',
    title: 'Десять контрактов',
    description: 'Закрыл серию из десяти контрактов.',
    rarity: 'rare',
    tags: ['contracts'],
  },
  {
    id: 'badge_incident_resolver',
    title: 'Пожарник',
    description: 'Успешно решил сложный инцидент.',
    rarity: 'rare',
    tags: ['incident'],
  },
  {
    id: 'badge_exam_speed',
    title: 'Экзамен на скорости',
    description: 'Показал отличный результат в короткое время.',
    rarity: 'epic',
    tags: ['exam'],
  },
] as const;
